### ISSUE TITLE
Marked as malicious and removed from Chrome web store

### ISSUE THREAD

**Issue by bubba2k** [ingui-n/musescore-downloader#1]
Seems like they marked this addon as malicious and removed it from the Chrome web store, rendering it unusable.
I do enjoy this extension for educational purposes; would you mind adding instructions on how to build it yourself?

**Comment by ingui-n** [comment]
Yes, Musescore reported the extension in the Chrome web store and they removed it. Sure, I can make an installation guide.

**Comment by ingui-n** [comment]
Installation guide is now in the README.md file. Enjoy

**Comment by bubba2k** [comment]
Thanks :)
