### ISSUE TITLE
Downloader doesn't work on some links

### ISSUE THREAD

**Issue by Shadow-Vortex** [ingui-n/musescore-downloader#11]
It appears that sometimes the downloader doesn't work when the creator of the piece has a unique ID name in the system (as in the URL uses a name of some sort instead of /user/#######/scores...) I haven't explored the issue very much yet, but here are some screenshots showing how it doesn't work sometimes.
![Screenshot 2023-12-02 165912](https://github.com/ingui-n/musescore-downloader/assets/71780305/c7b360b9-592b-4a45-b71c-88968eb0a115)
![Screenshot 2023-12-02 170035](https://github.com/ingui-n/musescore-downloader/assets/71780305/18c469f9-b23a-4d59-a0f7-8b31e07b79ad)

**Comment by Shadow-Vortex** [comment]
btw thanks for creating this extension, its been super useful

**Comment by ingui-n** [comment]
Hi, 
It has been a couple of weeks, so have you tried to see if the issue has been resolved on your device?

**Comment by Shadow-Vortex** [comment]
Yes, the issue is fixed. I can now download the pdf regardless of the link format. Thank you!
