### ISSUE TITLE
Unable to download certain sheets

### ISSUE THREAD

**Issue by Cheestastic** [ingui-n/musescore-downloader#19]
So when trying to download this sheet as audio or midi https://musescore.com/user/64917/scores/12282610 the file downloaded was just called 'mid' or 'mp3' with the file type simply being 'File'. When opening with notepad or word it's just a bunch of weird text.
![Screenshot 2024-09-10 154801](https://github.com/user-attachments/assets/38d165d5-35e7-4230-88a5-2fa031ae422a)

**Comment by ingui-n** [comment]
Hello,
if you simply rename the downloaded MIDI file to `filename.mid` and the audio file to `filename.mp3` it should work as normal. 

This likely happened because these files don't have any name, which is weird.

Thank you for reporting the bug, I will try to fix it

**Comment by Cheestastic** [comment]
Renaming the file did the trick. I believe this happened because the sheet name was in Japanese. I appreciate this extension, thanks a lot fam.

**Comment by ingui-n** [comment]
New version (0.5.9) is now available in both web stores. Please try yourself if works on your device too.
Thank you
