### ISSUE TITLE
Installation mode outdated

### ISSUE THREAD

**Issue by Flavio0834** [ingui-n/musescore-downloader#2]
Hello,

Following instructions on README.md here : https://github.com/ingui-n/musescore-downloader
I couldn't install the extension.
Automatic mode : "Can't install from this website" after downloading the package, when installing it.
Manual mode : "Incorrect package : CRX_REQUIRED_PROOF_MISSING" at the same stage, during installation.

I saw older instructions on old commits and on 0.4.2's README.md saying to download ZIP and use developer mode, **IT WORKS**.

Thanks for your work ! And sorry if error messages aren't exactly translated, I used a french version of Chrome.

**Comment by ingui-n** [comment]
Hi,
It looks like Google Chrome banned installing lokal .crx files. However it works in Opera 87.0.4390.25. Sadly I think there is no other option than install the extension manually for Chrome. 
Sorry for the inconvenience wish you still like the extension.

**Comment by Flavio0834** [comment]
Thanks for your fast reply.

I was just opening this issue in case you want to change the README.md, and this could help other people.
Of course I still like the extension, thanks again for your work !
