### ISSUE TITLE
pages not filling paper

### ISSUE THREAD

**Issue by chrpai** [ingui-n/musescore-downloader#21]
This is a very easy to use tool except for one problem.  When I download a score the pages in the PDF are too small and don't fit the usuable space.  I tried running the PDF through some additional tools such as print to pdf  and online tools telling it to stretch to the usable space but that doesn't work either.

<img width="290" alt="image" src="https://github.com/user-attachments/assets/6c0ba2b0-37d4-42c5-8eb7-edc33bf8c7f1">

**Comment by chrpai** [comment]
Correction... printing  to pdf with a custom scale of 135% helps.  It would be nice to not have to do this though.

**Comment by ingui-n** [comment]
Hello, thank you for creating the issue.
Could you please send me an URL of this score?

**Comment by chrpai** [comment]
https://musescore.com/user/39593079/scores/17092228

**Comment by ingui-n** [comment]
Hello, I think that I managed to fix the issue. It should be working in new version labeled 0.5.10
