### ISSUE TITLE
Open/Download Sheet stuck in "Please wait"

### ISSUE THREAD

**Issue by jcmcken** [ingui-n/musescore-downloader#3]
I tried this on the latest Chrome and Brave and see the same behavior. I see some elements updating, but nothing ends up happening. Perhaps something in the Musescore UI has changed, not sure

**Comment by ingui-n** [comment]
Hello,
I tried to reproduce your problem, but everything worked as it should. What operating system does your device use? Are all functions broken or do some of them work?
My testing setup:
OS: Windows 10, Manjaro Linux
Web browser: Opera, Chrome and Brave

**Comment by vaneess** [comment]
> I tried this on the latest Chrome and Brave and see the same behavior. I see some elements updating, but nothing ends up happening. Perhaps something in the Musescore UI has changed, not sure

same here
OS: Windows 11 22H2
Browser: Chrome 108.0.5359.125

i had to download your zip, and follow the readme in there. the readme on github and the seperate .crx file didn't work

**Comment by ingui-n** [comment]
Hi,
I just edited the [README.md](https://github.com/ingui-n/musescore-downloader/blob/master/README.md) file so it should be more helpful now. I gonna look in to the stuck at loading part now.

**Comment by ingui-n** [comment]
Please install the new version. The new version is available on https://chrome.google.com/webstore/detail/music-score-downloader/jhogldboghgffknljgnomjkcfbapogdf/
