### ISSUE TITLE
It's broken now

### ISSUE THREAD

**Issue by PikaPikaGamer** [ingui-n/musescore-downloader#4]
Midis, sheet music, everything has been patched. What a shame :(

**Comment by ingui-n** [comment]
Hello,
I tried to reproduce your issue, but from some unknown reason everything worked as it should. What operating system does your device use? What web browser are you using?
My testing setup:
OS: Windows 10, Manjaro Linux
Web browser: Opera, Chrome and Brave

Thank you in advance for your reply

**Comment by NickXDD** [comment]
Just checking in to confirm the same issue.

My testing setup:
OS: Windows 10
Web browser: Edge and Vivaldi

**Comment by ingui-n** [comment]
Please install the new version. The new version is available on https://chrome.google.com/webstore/detail/music-score-downloader/jhogldboghgffknljgnomjkcfbapogdf/
